MAKE=make
MAKECMDGOALS=

default:
	@$(MAKE) -C chap04 $(MAKECMDGOALS)
	@$(MAKE) -C chap05 $(MAKECMDGOALS)
	@$(MAKE) -C chap06 $(MAKECMDGOALS)
	@$(MAKE) -C chap07 $(MAKECMDGOALS)
	@$(MAKE) -C chap08 $(MAKECMDGOALS)
	@$(MAKE) -C chap09 $(MAKECMDGOALS)

all:
	@$(MAKE) -C chap04 $(MAKECMDGOALS) all
	@$(MAKE) -C chap05 $(MAKECMDGOALS) all
	@$(MAKE) -C chap06 $(MAKECMDGOALS) all
	@$(MAKE) -C chap07 $(MAKECMDGOALS) all
	@$(MAKE) -C chap08 $(MAKECMDGOALS) all
	@$(MAKE) -C chap09 $(MAKECMDGOALS) all

clean:
	@$(MAKE) -C chap04 $(MAKECMDGOALS) clean
	@$(MAKE) -C chap05 $(MAKECMDGOALS) clean
	@$(MAKE) -C chap06 $(MAKECMDGOALS) clean
	@$(MAKE) -C chap07 $(MAKECMDGOALS) clean
	@$(MAKE) -C chap08 $(MAKECMDGOALS) clean
	@$(MAKE) -C chap09 $(MAKECMDGOALS) clean
